name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            platform: win-x64
            path: D:\a\Tale\Tale\bin\Release\net7.0\win-x64\publish\*
            name: tale-win

          - os: macos-latest
            platform: osx-x64
            path: /Users/runner/work/Tale/Tale/bin/Release/net7.0/osx-x64/publish/*
            name: tale-osx

          - os: ubuntu-latest
            platform: linux-x64
            path: /home/runner/work/Tale/Tale/bin/Release/net7.0/linux-x64/publish/*
            name: tale-linux

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: |
        dotnet publish -r ${{ matrix.platform }} -c Release --self-contained true

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.path }}